[tool.poetry]
name = "django-boilerplate"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.0.8"
whitenoise = "^5.1.0"
dj-database-url = "^0.5.0"
python-decouple = "^3.3"
psycopg2-binary = "^2.8.5"
gunicorn = "^20.0.4"
django_compressor = "^2.4"
libsass = "^0.20.0"
unipath = "^1.1"

[tool.poetry.dev-dependencies]
model-bakery = "^1.1.0"
pytest = "^5.4.3"
pytest-django = "^3.9.0"
